# generated by datamodel-codegen:
#   filename:  ogcapppkg.yaml
#   timestamp: 2021-07-22T21:42:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import AnyUrl, BaseModel, Field, PositiveFloat, conint


class Metadata(BaseModel):
    title: Optional[str] = None
    role: Optional[str] = None
    href: Optional[str] = None


class AdditionalParameter(BaseModel):
    name: str
    value: List[Union[str, float, int, List, Dict[str, Any]]]


class JobControlOptions(Enum):
    sync_execute = 'sync-execute'
    async_execute = 'async-execute'
    dismiss = 'dismiss'


class TransmissionMode(Enum):
    value = 'value'
    reference = 'reference'


class Link(BaseModel):
    href: str
    rel: Optional[str] = Field(None, example='service')
    type: Optional[str] = Field(None, example='application/json')
    hreflang: Optional[str] = Field(None, example='en')
    title: Optional[str] = None


class MaxOccurEnum(Enum):
    unbounded = 'unbounded'


class TypeEnum(Enum):
    array = 'array'
    boolean = 'boolean'
    integer = 'integer'
    number = 'number'
    object = 'object'
    string = 'string'


class Reference(BaseModel):
    _ref: str = Field(..., alias='$ref')


class AdditionalParameters(Metadata):
    parameters: Optional[List[AdditionalParameter]] = None


class DescriptionType(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    keywords: Optional[List[str]] = None
    metadata: Optional[List[Metadata]] = None
    additionalParameters: Optional[AdditionalParameters] = None


class ProcessSummary(DescriptionType):
    id: str
    version: str
    jobControlOptions: Optional[List[JobControlOptions]] = None
    outputTransmission: Optional[List[TransmissionMode]] = None
    links: Optional[List[Link]] = None


class Process(ProcessSummary):
    inputs: Optional[Any] = None
    outputs: Optional[Any] = None


class OGCAppPackage(BaseModel):
    immediateDeployment: Optional[bool] = None
    processDescription: Process
    executionUnit: List[Dict[str, Any]] = Field(..., min_items=1)
    deploymentProfile: AnyUrl = Field(
        ...,
        example='http://www.opengis.net/profiles/eoc/dockerizedApplication'
    )


class SchemaModel(BaseModel):
    __root__: Union[Reference, SchemaItem]


class SchemaItem(BaseModel):
    title: Optional[str] = None
    multipleOf: Optional[PositiveFloat] = None
    maximum: Optional[float] = None
    exclusiveMaximum: Optional[bool] = False
    minimum: Optional[float] = None
    exclusiveMinimum: Optional[bool] = False
    maxLength: Optional[conint(ge=0)] = None
    minLength: Optional[conint(ge=0)] = 0
    pattern: Optional[str] = None
    maxItems: Optional[conint(ge=0)] = None
    minItems: Optional[conint(ge=0)] = 0
    uniqueItems: Optional[bool] = False
    maxProperties: Optional[conint(ge=0)] = None
    minProperties: Optional[conint(ge=0)] = 0
    required: Optional[List[str]] = Field(None, min_items=1)
    enum: Optional[List] = Field(None, min_items=1)
    type_: Optional[TypeEnum] = Field(None, alias='type')
    not_: Optional[Union[SchemaModel, Reference]] = Field(None, alias='not')
    allOf: Optional[List[Union[SchemaModel, Reference]]] = None
    oneOf: Optional[List[Union[SchemaModel, Reference]]] = None
    anyOf: Optional[List[Union[SchemaModel, Reference]]] = None
    items: Optional[Union[SchemaModel, Reference]] = None
    properties: Optional[Dict[str, Union[SchemaModel, Reference]]] = None
    additionalProperties: Optional[Union[SchemaModel, Reference, bool]] = True
    description: Optional[str] = None
    format_: Optional[str] = Field(None, alias='format')
    default: Optional[Any] = None
    nullable: Optional[bool] = False
    readOnly: Optional[bool] = False
    writeOnly: Optional[bool] = False
    example: Optional[Any] = None
    deprecated: Optional[bool] = False
    contentMediaType: Optional[str] = None
    contentEncoding: Optional[str] = None
    contentSchema: Optional[str] = None


class InputDescription(DescriptionType):
    minOccurs: Optional[int] = 1
    maxOccurs: Optional[Union[int, MaxOccurEnum]] = None
    schema_: SchemaModel = Field(..., alias='schema')


class OutputDescription(DescriptionType):
    schema_: SchemaModel = Field(..., alias='schema')


InputDescription.update_forward_refs()
OutputDescription.update_forward_refs()
SchemaItem.update_forward_refs()
